### ISSUE TITLE
Exception thrown: 'System.MissingMethodException' in WebOptimizer.Less.dll

### ISSUE THREAD

**Issue by kdcllc** [ligershark/WebOptimizer.Less#1]
@madskristensen, I am getting this exception when attempted to compile LESS and Typescript in the same project. 

LigerShark.WebOptimizer.TypeScript - 2.5.8-beta
LigerShark.WebOptimizer.LESS - 2.7.2-beta

```
                pipeline.AddLessBundle("/app-styles.css", "App/Css/**/*.less")
                        .UseContentRoot();

                pipeline.AddTypeScriptBundle("/js/app.js", "App/**/*.ts")
                        .UseContentRoot();
```
```
Exception thrown: 'System.MissingMethodException' in WebOptimizer.Less.dll
An exception of type 'System.MissingMethodException' occurred in WebOptimizer.Less.dll but was not handled in user code
Method not found: 'WebOptimizer.IAssetPipeline WebOptimizer.IAsset.get_Pipeline()'.
```
And

```
   at Microsoft.Extensions.DependencyInjection.TypeScriptPipelineExtensions.CompileLess(IAsset asset)
   at Microsoft.Extensions.DependencyInjection.TypeScriptPipelineExtensions.AddLessBundle(IAssetPipeline pipeline, String route, String[] sourceFiles)
   at BitShuva.Chavah.Startup.<>c.<ConfigureServices>b__4_0(IAssetPipeline pipeline) in C:\Dev\GitHub\Chavah\Chavah.NetCore\Startup.cs:line 62
   at Microsoft.Extensions.DependencyInjection.ServiceExtensions.AddWebOptimizer(IServiceCollection services, Action`1 assetPipeline)
   at BitShuva.Chavah.Startup.ConfigureServices(IServiceCollection services) in C:\Dev\GitHub\Chavah\Chavah.NetCore\Startup.cs:line 60
```

Any pointers would be greatly appreciated!

**Comment by twenzel** [comment]
We‘re also getting this error. A fixed and updated NuGet package would be awesome. Do you Need and help?

**Comment by madskristensen** [comment]
I just pushed a new build. It will take ~20 minutes to be live on NuGet. Please let me know if it fixes the issue

**Comment by twenzel** [comment]
Great! It's working now.

**Comment by dharmeshtailor** [comment]
Hi I am getting similar error while using WebOptimizer.Less and WebOptimizer.Core in same project

    LigerShark.WebOptimizer.Core Version="3.0.384"
    LigerShark.WebOptimizer.LESS Version="2.7.7-beta"

```
             pipeline.AddLessBundle("/content/xxx.css",
                "content/less/xxx.less");

            pipeline.AddLessBundle("/content/something.css",
                "content/less/something.less");

            pipeline.AddLessBundle("/content/xxx.css",
                "content/less/xxx.less");

            pipeline.AddLessBundle("/content/xxx.css",
                "content/less/xx.less");
```

```
info: WebOptimizer.AssetMiddleware[1000]
      Request started for '/content/something.css'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.MissingMethodException: Method not found: 'Microsoft.Extensions.FileProviders.IFileProvider WebOptimizer.AssetExtensions.GetFileProvider(WebOptimizer.IAsset, Microsoft.AspNetCore.Hosting.IHostingEnvironment)'.
         at WebOptimizer.Less.LessProcessor.ExecuteAsync(IAssetContext context)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at WebOptimizer.Less.LessProcessor.ExecuteAsync(IAssetContext context)
         at WebOptimizer.Asset.ExecuteAsync(HttpContext context, IWebOptimizerOptions options)
         at WebOptimizer.AssetBuilder.BuildAsync(IAsset asset, HttpContext context, IWebOptimizerOptions options)
         at WebOptimizer.AssetMiddleware.HandleAssetAsync(HttpContext context, IAsset asset, WebOptimizerOptions options)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
